### ISSUE TITLE
FPs due to incorrect floor price

### ISSUE THREAD

**Issue by christian-forta** [Kayaba-Attribution/scammer-nft-trader#4]
https://etherscan.io/tx/0x24f20b56d9c3554595cfee2fd961fd82a49568e61cab63ddfcbbe4c727da710f. Seems like the floor price is off on what the bot uses.

I wonder whether we need to utilize 2 APIs to get a reliable floor price feed?

**Comment by Kayaba-Attribution** [comment]
Thank you for the observation @christian-forta , integrated a second floorPrice feed using [OpenSea API V1](https://docs.opensea.io/v1.0/reference/api-overview) on this [commit](https://github.com/Kayaba-Attribution/scammer-nft-trader/commit/ced66db33c574b79724c18a70798fe014ed3bfd9)

The agent:
+ Uses Alchemy by default
+ Uses OpenSea when the Alchemy returns 0 or null.
+ If both feeds return a number it uses the min between the 2

the tx 0x24f20b56d9c3554595cfee2fd961fd82a49568e61cab63ddfcbbe4c727da710f will now display:

```bash
1 findings for transaction 0x24f20b56d9c3554595cfee2fd961fd82a49568e61cab63ddfcbbe4c727da710f {
  "name": "scammer-nft-trader",
  "description": "[Opensea 🌊] Art Blocks id 457000690 sold at 0.320 ETH with collection floor of 1.0000 ETH (-68.00%)",
  "alertId": "nft-sale",
  "protocol": "ethereum",
  "severity": "Info",
  "type": "Info",
  "metadata": {
    "interactedMarket": "opensea",
    "transactionHash": "0x24f20b56d9c3554595cfee2fd961fd82a49568e61cab63ddfcbbe4c727da710f",
    "toAddr": "0x837b24455dc3796b1a91707741c8162fbb71c5d6",
    "fromAddr": "0x1b49504d0ba12df901b94bae3597c27afaf40007",
    "initiator": "0x837b24455dc3796b1a91707741c8162fbb71c5d6",
    "totalPrice": "0.32",
    "avgItemPrice": "0.32",
    "contractAddress": "0x99a9b7c1116f9ceeb1652de04d5969cce509b069",
    "floorPrice": "1",
    "timestamp": "1687378739",
    
```
